plugins {
    id 'dev.architectury.loom' version '1.11-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.gradleup.shadow' version '8.3.6' apply false
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        archivesName = "$rootProject.archives_name-$project.name"
    }

    repositories {
        mavenCentral()
        maven {
            name = "CurseMaven"
            url = "https://cursemaven.com"
        }
        maven { // JEI
            name = "Jared's maven"
            url = "https://maven.blamejared.com/"
        }
        maven { // EMI
            name = "TerraformersMC Maven"
            url = "https://maven.terraformersmc.com/"
        }
        maven { // Architectury
            name = "Shedaniel Maven"
            url = "https://maven.shedaniel.me/"
        }
        maven {// FTB
            name = "FTB Maven"
            url = "https://maven.ftb.dev/releases/"
        }
        maven {// Xaero lib
            url "https://chocolateminecraft.com/maven"
            name "Xaero's Maven"
        }
    }

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.officialMojangMappings()
        
        modCompileOnly "org.projectlombok:lombok:1.18.42"
        annotationProcessor "org.projectlombok:lombok:1.18.42"

        modCompileOnly "mezz.jei:jei-1.20.1-forge-api:15.20.0.116"
        modRuntimeOnly "mezz.jei:jei-1.20.1-forge:15.20.0.116"
        
        modCompileOnly "dev.emi:emi-forge:${emi}:api"
        modRuntimeOnly "dev.emi:emi-forge:${emi}"

        modImplementation "xaero.lib:xaerolib-forge-1.20:1.0.42"
        modImplementation "curse.maven:xaeros-minimap-263420:7400975"
        modImplementation "curse.maven:xaeros-world-map-317780:7401084"

        modImplementation "dev.architectury:architectury-forge:${architectury}"
        modImplementation "dev.ftb.mods:ftb-library-forge:${ftb_lib}"
        modImplementation "dev.ftb.mods:ftb-teams-forge:${ftb_teams}"
        modImplementation "dev.ftb.mods:ftb-chunks-forge:${ftb_chunks}"
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }

        repositories {
            
        }
    }
}
