# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties

mod_version = 1.1.4
maven_group = dev.satherov.ftbxaerocompat
archives_name = ftbxaerocompat
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies

architectury_api_version = 13.0.8
fabric_loader_version = 0.17.2
fabric_api_version = 0.116.6+1.21.1
neoforge_version = 21.1.209

emi=1.1.22+1.21.1
architectury=13.0.8
ftb_lib=2101.1.31
ftb_teams=2101.1.10
ftb_chunks=2101.1.14

worldmap=1.40.16
minimap=25.3.13
lib=1.1.15